# Generated by Django 5.2.6 on 2025-09-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daysctivity',
            new_name='daysactivity',
        ),
    ]
