# Generated by Django 5.2.6 on 2025-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_daysctivity_daysactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysactivity',
            name='title',
            field=models.CharField(),
        ),
    ]
