# Generated by Django 5.2.6 on 2025-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_daysactivity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysactivity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='daysactivity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysactivity',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
